### ISSUE TITLE
 dataset link invalid

### ISSUE THREAD

**Issue by fsted** [AutoAILab/M2CP-Learning#1]
Hello, thank you for your code. This is an excellent paper, but the dataset link seems to be invalid. Could you update it?😄

**Comment by Zhimin-C** [comment]
Thanks for your interest in our work. I have updated the link. For free to contact me for any other questions.

**Comment by fsted** [comment]
> Thanks for your interest in our work. I have updated the link. For free to contact me for any other questions.

Thank you ！
