### ISSUE TITLE
The program is stuck in the data loading step

### ISSUE THREAD

**Issue by fsted** [AutoAILab/M2CP-Learning#2]
Hello, thank you for updating the data link,But I still encountered a strange problem. 
The program did not report an error,but stuck in the part of data loading,that is:
M2CP-Learning/train.py:116:
       ` for l_data, u_data in zip (labeled_data_loader, unlabeled_data_loader):`
The program seems to stay in a certain loading phase. Do you have any clue about this,Thanks！

**Comment by Zhimin-C** [comment]
Hello, I think it is caused by problems in the data loader, but I cannot solve this problem only with current information. May you provide the specific error by the screenshot or just copying from the terminal.

**Comment by fsted** [comment]
> Hello, I think it is caused by problems in the data loader, but I cannot solve this problem only with current information. May you provide the specific error by the screenshot or just copying from the terminal.

Thank you for your suggestion. I have solved this problem. Just set num_ Workers=0 can run smoothly, thank you😄
