### ISSUE TITLE
A little question about testing

### ISSUE THREAD

**Issue by OnePointFive99** [AutoAILab/M2CP-Learning#3]
It has been observed that the image data used during testing is selected randomly, which could potentially result in fluctuations in the test outcomes. What is your opinion on this matter?

**Comment by Zhimin-C** [comment]
There are more than 12 rendered images for each point cloud instance in the provided dataset so we have to randomly choose a fixed number of images during the testing. I think some people may provide rendered images dataset that has less than 12 images for each point instance. You may try such a dataset to avoid fluctuations.

**Comment by OnePointFive99** [comment]
Thank you for taking the time to provide an answer to my previous question, and I truly appreciate the value of your work. I was hoping to ask another question regarding the code, specifically inquiring as to the reasoning behind the inclusion of the line 'iteration = iteration + 1' twice in the code：https://github.com/AutoAILab/M2CP-Learning/blob/ca75b307d51d44f518bd2b6950da858cfa77fda5/train.py#L325-L351
Would you be able to kindly explain this to me?

**Comment by Zhimin-C** [comment]
Thanks for your interest in this work. It is just a mistake; I have fixed this issue in the code.

Zhimin Chen

**Comment by OnePointFive99** [comment]
Thank you for taking the time to answer my question. I would like to close this issue.
